name: install

on: [push, pull_request]

jobs:
  test-powershell:
    name: Install it on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ghcman
    - name: Install powershell-yaml
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module powershell-yaml -Force
    - name: Install it
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $DebugPreference = 'Continue'
        Import-Module .\ghcman
        Update-GhcmanVersionFile 4.10
        Install-Ghc 9.2.1 -Force
        Get-Ghc -HumanReadable
